name: my-app
version: v1
image:
  name: quay.io/kubermatic-labs/training-application
  tag: 4.0.0
color: white
message: "Hello from the app installed via helm"
catMode: true
persistMetaInfo: false

deployment:
  replicas: 1

service:
  type: ClusterIP

ingress:
  enabled: false
  domain: example.com

gateway:
  enabled: false
  name: my-gateway
  namespace: gateway
  hostnames: []
