kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: training
kubeadmConfigPatches:
  - |
    kind: KubeletConfiguration
    systemReserved:
      cpu: "2"
      memory: "4Gi"
nodes:
  - role: control-plane
  - role: worker
